name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      # Check out the repository code to the runner

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.14.0'
        cache: 'npm'  
      # Set up the Node.js environment with the specified version and enable npm caching

    - name: Install Dependencies
      run: npm ci  
      # Install project dependencies using a clean install

    - name: Run Cypress Tests
      run: npm run cypress:run -- --reporter junit --reporter-options "mochaFile=results/test-results.xml"
      env:
        CYPRESS_BASE_URL: "https://www.saucedemo.com"  
        CI: true
      # Run Cypress tests with JUnit reporter and set the base URL for tests

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: cypress-test-results
        path: results/test-results.xml
      # Upload the test results as an artifact for later use
