name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Cypress Tests
      run: npm run cypress:run
      env:
        CYPRESS_BASE_URL: "https://www.saucedemo.com"
        CI: true
      continue-on-error: true
      # This allows the workflow to continue even if Cypress tests fail, so we can upload artifacts.

    - name: Ensure Cypress Screenshots Directory Exists
      run: mkdir -p cypress/screenshots

    - name: Upload Cypress Screenshots (always)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress/screenshots

    - name: Ensure Cypress Videos Directory Exists
      run: mkdir -p cypress/videos

    - name: Upload Cypress Videos (always)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: cypress/videos
    